#language: haskell
services:
- docker
before_install:
- docker pull haskell
- docker pull jamesmstone/hlint
script:
- docker run --rm -v"$(pwd)":/hlint -w/hlint jamesmstone/hlint ./Proj1.hs
- docker run -it --rm -v"$(pwd)":/haskell -w/haskell haskell ghc -O2 --make Proj1testJames && ./Proj1testJames
- docker run -it --rm -v"$(pwd)":/haskell -w/haskell haskell ghc -O2 --make Proj1test
- ./Proj1test AH 2C 3D 4S
- ./Proj1test AH 2C 3D
- ./Proj1test AH 2C
- ./Proj1test AH 2H 3H 4H
- ./Proj1test AH AC AD AS
